// <auto-generated />
using DbComplimentYoutubeImdb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbComplimentYoutubeImdb.Migrations
{
    [DbContext(typeof(ContextComplimentYoutubeImdb))]
    partial class ContextComplimentYoutubeImdbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DbComplimentYoutubeImdb.MovieLink", b =>
                {
                    b.Property<string>("ImdbID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PosterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImdbID");

                    b.ToTable("MovieLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
